kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: app-city
  name: app-city-service
  namespace: default
spec:
  externalIPs: ['192.168.0.254']
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    k8s-app: app-city

---

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: app-city
  name: app-city-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: app-city
  template:
    metadata:
      labels:
        k8s-app: app-city
    spec:
      containers:
        - name: nginx-name
          image: nginx:1.17.10-alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
