apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: name-virtual-host-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: home.mcgilln.com
    http:
      paths:
      - path: /
        backend:
          serviceName: app-city-service
          servicePort: 80
  - http:
      paths:
      - path: /(/|$)(.*)
        backend:
          serviceName: app-city-service
          servicePort: 80
