apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: name-virtual-host-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: foo.kevin.local
    http:
      paths:
      - path: /test
        pathType: Prefix
        backend:
          serviceName: app-city-service
          servicePort: 80
